### ISSUE TITLE
Install @playwright/test notification showing on activation, despite being installed

### ISSUE THREAD

**Issue by Tyriar** [microsoft/playwright-vscode#114]
I'm seeing this whenever I open my workspace:

![image](https://user-images.githubusercontent.com/2193314/155225615-270e25f4-c5d8-453d-a738-61fdf24028a2.png)

My project is structures like this which is maybe the reason:

```
outer-project
  package.json
  node_modules
  sub-project (git module) <-- this is the opened folder
    package.json
    node_modules <-- this is where @playwright/test is installed
```

So the first problem is that I'm getting the notification at all. It also occurs to me that you shouldn't be showing a notification on activation or startup but when the extension actually needs to use the extension, otherwise it would just be annoying and add to many notifications popping up when syncing settings, opening vscode.dev, etc.

**Comment by pavelfeldman** [comment]
Extension is activated when it finds playwright.config.ts in your workspace. I assume you have one, so it activates. It will then go ahead and try running `require.resolve("@playwright/test")` from that config folder. It does that in order to populate the Test tree and render the editor decorators. Until it parses the config, any file potentially has test decorations, so parsing the config lazily does not save much.

Does running `node -e "require.resolve('@playwright/test')"` in your config folder succeed?

**Comment by Tyriar** [comment]
Notes from our call:

- Notification on startup is a bad experience when opening a folder without node_modules installed for example
  - Only show the notification if node_modules is not installed seems like a good compromise
- Bad experience for older versions apparently is the root cause of https://github.com/microsoft/playwright-vscode/issues/114
  - I was on `@playwright/test@1.14.1`
- Have 2 playwright.config files, tests are duplicated in out (js) and src (ts) because of that
- `src`/`out` folder was missing from config names 
  ![image](https://user-images.githubusercontent.com/2193314/155237345-4ca591f9-a8e0-4fc1-acb4-88c945569d33.png)
- I cannot expand any of the items (related to compiled mode) 
  ![image](https://user-images.githubusercontent.com/2193314/155237316-26086705-42d1-43ec-ac5d-172ea5f3073a.png)
- `.test.d.ts` files were showing up in tests

**Comment by pavelfeldman** [comment]
> Notification on startup is a bad experience when opening a folder without node_modules installed for example

I'll remove those from the activation. It'll silently not work until user presses the 'Reload tests' button

> Bad experience for older versions

Following up with a fix

> Have 2 playwright.config files, tests are duplicated in out (js) and src (ts) because of that

That's by design, you can have several configs and they all will be loaded, compiling config would be unusual.

> src/out folder was missing from config names

I did not want to print the whole path to config here, could be long. So I was disambiguating them using immediate parent. In your case parents have the same name. I'd still say unusual / low pri.

> I cannot expand any of the items (related to compiled mode)

Compiled mode is not yet supported in the extension. We'll prioritize it based on the usage / reports.

**Comment by pavelfeldman** [comment]
Does not look actionable at this point, let's split into explicit requests for remaining issues.
