### ISSUE TITLE
Hide empty workspace folders

### ISSUE THREAD

**Issue by baptisteArno** [microsoft/playwright-vscode#155]
I have a monorepo with lots of folders but only 2 apps have Playwright tests:

<img width="368" alt="CleanShot 2022-04-23 at 09 49 08@2x" src="https://user-images.githubusercontent.com/16015833/164915655-d63452d2-43bc-459f-8ba0-37e2da4acea6.png">

That would be nice to be able to hide the other folders. There's an option in the context menu but when restarting VSCode it still shows up

**Comment by Camo30** [comment]
I have nearly the same folder structure in my monorepo. The tests are deeply nested in some subfolder while the main configuration file is in the root folder (because otherwise the extension fails to find the configuration file). This way the extension shows the whole folder structure in collapsed state and I always need to expand them one by one.

In my opinion the best way to solve this would be some configuration option to (optionally) set the path to the configuration file. This way the extension could use the folder with the configuration file as base folder.

**Comment by pavelfeldman** [comment]
> (because otherwise the extension fails to find the configuration file)

This actually should not be the case, it'll traverse the entire workspace. Not saying the issue should not be addressed, but you should totally be able to place your config files into the respective monorepo folders. That's what we do.

Note that there is a drop box next to Play and Debug buttons in the Testing toolbar. They allow picking the current config files that will run as you press those buttons.

**Comment by Camo30** [comment]
@pavelfeldman Yes, you are right - my fault. My configuration file was named `playwright.conf.ts` which is why it wasn't found.

**Comment by pavelfeldman** [comment]
Closing as per above. Please feel free to open new issues for the remaining work items.
