### ISSUE TITLE
Bug: Tests not discovered

### ISSUE THREAD

**Issue by MarcusFelling** [microsoft/playwright-vscode#84]
**Context:**
- Playwright Version: 1.19.0-alpha-feb-4-2022
- vsix built from https://github.com/microsoft/playwright-vscode/commit/b1ea5d371c52cf65ff80368fbac586a58ba89ecb
- system: 
![image](https://user-images.githubusercontent.com/6855361/152560698-ff5fd2be-3320-44b0-9916-86c349fe8e26.png)

**Repro:**
1. Extract [does-not-work.zip](https://github.com/microsoft/playwright-vscode/files/8004604/does-not-work.zip), then open in VS Code
2. npm i

Result:
No tests found
![image](https://user-images.githubusercontent.com/6855361/152565119-37259592-229d-411f-9a08-2c5da2c1d9c7.png)

Error
![image](https://user-images.githubusercontent.com/6855361/152564283-40bfc6f4-f6b7-47ae-9311-822d48f11f2b.png)

Using the same steps with [works.zip](https://github.com/microsoft/playwright-vscode/files/8004605/works.zip) discovers tests.

**Comment by pavelfeldman** [comment]
If you try running `npx playwright test` in the root folder of your workspace it won't work either, npm commands won't work too. The reason is that your node_modules are in a subfolder, hence not used. While I can support this kind of a use case, it is unusual, you should be opening the folder that has `package.json` in VSCode if you want to use it as something more than an editor.

**Comment by pavelfeldman** [comment]
Should be fixed now.
